version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_SERVER=${DB_SERVER}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - assembly-network

  chatbot:
    build: ./chatbot
    ports:
      - "8001:8001"
    environment:
      - BACKEND_API_URL=http://backend:8000
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    networks:
      - assembly-network

networks:
  assembly-network:
    driver: bridge
